fix: import of photoswipe causes error at runtime
When clicking on an image in the demo, the following error was thrown:
  TypeError: (photoswipe__WEBPACK_IMPORTED_MODULE_0___namespace_cache || photoswipe__WEBPACK_IMPORTED_MODULE_0___namespace_cache) is not a constructor